In [248]:
import pandas as pd
import numpy as np

### 1. Concatenando as bases de dados

In [249]:
df_2024_1 = pd.read_csv('dados/2024_1.csv', sep=';', decimal=',')
df_2024_2 = pd.read_csv('dados/2024_2.csv', sep=';', decimal=',')
df_2025_1 = pd.read_csv('dados/2025_1.csv', sep=';', decimal=',')
df_2025_2 = pd.read_csv('dados/2025_2.csv', sep=';', decimal=',')
df = pd.concat([df_2024_1, df_2024_2,df_2025_1, df_2025_2], ignore_index=True)

C:\Users\ian.iannacconi.SENACRJEDU.000\AppData\Local\Temp\ipykernel_12040\2790895961.py:3: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv('dados/2025_1.csv', sep=';', decimal=',')

In [250]:
df.columns

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='str')

### 2. Preço médio da gasolina c no estado do RJ por municipio

In [251]:
df_comun = df.loc[df['Produto'] == 'GASOLINA']

In [252]:
df_comun_rj_estado = df_comun.loc[df_comun['Estado - Sigla'] == 'RJ']
df_comun_munics_rj = df_comun_rj_estado.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_comun_munics_rj

                      Municipio  Valor de Venda
29                    TRES RIOS        6.591634
0                ANGRA DOS REIS        6.521620
18                   PETROPOLIS        6.479639
2                BARRA DO PIRAI        6.375640
11                        MACAE        6.364828
16                NOVA FRIBURGO        6.357044
10                    ITAPERUNA        6.352013
6         CAMPOS DOS GOYTACAZES        6.338306
5                     CABO FRIO        6.322089
23  SAO FRANCISCO DE ITABAPOANA        6.214804
31                VOLTA REDONDA        6.206265
1                      ARARUAMA        6.158700
27                    SAQUAREMA        6.133649
3                   BARRA MANSA        6.092928
30                      VALENCA        6.047609
26                     SAPUCAIA        5.994565
22       SANTO ANTONIO DE PADUA        5.962665
21               RIO DE JANEIRO        5.930698
13                       MARICA        5.899534
19                      RESENDE        5.885842
24                  SAO GONCALO        5.855353
20                   RIO BONITO        5.848639
8                      ITABORAI        5.842281
17                  NOVA IGUACU        5.807970
7               DUQUE DE CAXIAS        5.793860
25           SAO JOAO DE MERITI        5.780650
14                    NILOPOLIS        5.769526
15                      NITEROI        5.757424
4                  BELFORD ROXO        5.752965
12                         MAGE        5.615435
9                       ITAGUAI        5.602390
28                  TERESOPOLIS        5.508448

### 3. Outliers no estado do RJ, e estatísticas

In [270]:
df_comun_postos_rj = df_comun_rj_estado.groupby('Revenda')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_comun_postos_rj

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000
776                        POSTO SATURNO FRIBURGO LTDA        6.824444
1                   A C TRANCOZO M B COMBUSTIVEIS LTDA        6.742157
304  COMERCIO DE PETROLEO E DERIVADOS COND DO RIO N...        6.713529
..                                                 ...             ...
668                             POSTO FLAMAREDI EIRELI        5.282000
571              POSTO DE GASOLINA JARDIM SULACAP LTDA        5.226364
569              POSTO DE GASOLINA JAGUAR DO ANIL LTDA        5.156667
567                     POSTO DE GASOLINA ITAJUBA LTDA        5.090000
560                        POSTO DE GASOLINA GALP LTDA        5.090000

[872 rows x 2 columns]

In [271]:
array_comun_rj = np.array(df_comun_postos_rj['Valor de Venda'])
media_c_rj = np.mean(array_comun_rj)
mediana_c_rj = np.median(array_comun_rj)
q1_c_rj = np.percentile(array_comun_rj, 25)
q3_c_rj = np.percentile(array_comun_rj, 75)
distancia_c_rj = round(((media_c_rj - mediana_c_rj) / mediana_c_rj) * 100, 2)
iqr_c_rj = q3_c_rj - q1_c_rj
l_superior = q3_c_rj + (1.5*iqr_c_rj)
l_inferior = q1_c_rj - (1.5*iqr_c_rj)
print(f'Media: {media_c_rj} \nMediana: {mediana_c_rj} \nDistancia: {distancia_c_rj}% \nQ1: {q1_c_rj} Q3: {q3_c_rj}')
print(f'IQR: {iqr_c_rj} \nSuperior: {l_superior} \nInferior: {l_inferior}')

Media: 5.947818265606212
Mediana: 5.9136419461502125
Distancia: 0.58%
Q1: 5.692154135338346 Q3: 6.19
IQR: 0.49784586466165415
Superior: 6.936768796992482
Inferior: 4.945385338345865

O limite inferior não é negativo logo podem existir postos afetando a media

In [254]:
outlier_sup_c_rj = df_comun_postos_rj.loc[df_comun_postos_rj['Valor de Venda'] > l_superior]
outlier_sup_c_rj

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000

In [255]:
outlier_inf_c_rj = df_comun_postos_rj.loc[df_comun_postos_rj['Valor de Venda'] < l_inferior]
outlier_inf_c_rj

Empty DataFrame
Columns: [Revenda, Valor de Venda]
Index: []

### 4. Etanol Hidratado

In [256]:
df_etanol = df.loc[df['Produto'] == 'ETANOL']
df_etanol_rj = df_etanol.loc[df_etanol['Estado - Sigla'] == 'RJ']
df_etanol_sp = df_etanol.loc[df_etanol['Estado - Sigla'] == 'SP']

RJ:

In [257]:
array_etanol_rj = np.array(df_etanol_rj['Valor de Venda'])
media_e_rj = np.mean(array_etanol_rj)
q1_e_rj = np.percentile(array_etanol_rj, 25)
q3_e_rj = np.percentile(array_etanol_rj, 75)
iqr_e_rj = q3_e_rj - q1_e_rj
l_sup_e_rj = q3_e_rj + (1.5*iqr_e_rj)
l_inf_e_rj = q1_e_rj - (1.5*iqr_e_rj)
print(f'Media: {media_e_rj} \nQ1: {q1_e_rj} Q3: {q3_e_rj}')
print(f'IQR: {iqr_e_rj} \nSuperior: {l_sup_e_rj} \nInferior: {l_inf_e_rj}')

Media: 4.4344866618124055
Q1: 4.19 Q3: 4.69
IQR: 0.5
Superior: 5.44
Inferior: 3.4400000000000004

In [258]:
outlier_sup_e_rj = df_etanol_rj.loc[df_etanol_rj['Valor de Venda'] > l_sup_e_rj]
outlier_sup_e_rj

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
321766,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,30/04/2024,5.45,NaN,R$ / litro,VIBRA
356851,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,14/05/2024,5.45,NaN,R$ / litro,VIBRA
392438,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,28/05/2024,5.45,NaN,R$ / litro,VIBRA
411406,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,04/06/2024,5.45,NaN,R$ / litro,VIBRA
428491,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,11/06/2024,5.45,NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507550,SE,RJ,ANGRA DOS REIS,AUTO POSTO ROBALO LTDA.,7817563000116,RODOVIA GOVERNADOR MÁRIO COVAS,1,KM 513,FRADE,23903-000,ETANOL,03/12/2025,5.47,NaN,R$ / litro,ALE
1508703,SE,RJ,NOVA IGUACU,POSTO KM 13 DA DUTRA LTDA,118442000137,RODOVIA PRESIDENTE DUTRA,13006,NaN,PRATA,26010-003,ETANOL,08/12/2025,6.39,NaN,R$ / litro,IPIRANGA
1514892,SE,RJ,ANGRA DOS REIS,AUTO POSTO ROBALO LTDA.,7817563000116,RODOVIA GOVERNADOR MÁRIO COVAS,1,KM 513,FRADE,23903-000,ETANOL,18/12/2025,5.53,NaN,R$ / litro,ALE
1519101,SE,RJ,ANGRA DOS REIS,AUTO POSTO ROBALO LTDA.,7817563000116,RODOVIA GOVERNADOR MÁRIO COVAS,1,KM 513,FRADE,23903-000,ETANOL,29/12/2025,5.56,NaN,R$ / litro,ALE
1519853,SE,RJ,SAO GONCALO,AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...,3741078000155,AVENIDA FRANCISCO DE AZEREDO COUTINHO,S/N,LOTE 24 A,SANTA IZABEL,24738-275,ETANOL,29/12/2025,5.59,NaN,R$ / litro,BRANCA

In [259]:
outlier_inf_e_rj = df_etanol_rj.loc[df_etanol_rj['Valor de Venda'] < l_inf_e_rj]
outlier_inf_e_rj

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
2566,SE,RJ,TERESOPOLIS,POSTO PODIUM DE TERESOPOLIS LTDA,05.564.689/0001-09,AVENIDA LUCIO MEIRA,2448,NaN,VARZEA,25953-004,ETANOL,02/01/2024,3.34,NaN,R$ / litro,BRANCA
6559,SE,RJ,SANTO ANTONIO DE PADUA,GNV PADUA COMERCIO DE COMBUSTIVEL LTDA - ME,15.252.610/0001-50,ESTRADA PADUA - PIRAPETINGA,SN,KM 01 GALPAO02,ARRAIALZINHO,28470-000,ETANOL,02/01/2024,3.44,NaN,R$ / litro,BRANCA
23704,SE,RJ,SANTO ANTONIO DE PADUA,GNV PADUA COMERCIO DE COMBUSTIVEL LTDA - ME,15.252.610/0001-50,ESTRADA PADUA - PIRAPETINGA,SN,KM 01 GALPAO02,ARRAIALZINHO,28470-000,ETANOL,08/01/2024,3.44,NaN,R$ / litro,BRANCA
29997,SE,RJ,TERESOPOLIS,POSTO PODIUM DE TERESOPOLIS LTDA,05.564.689/0001-09,AVENIDA LUCIO MEIRA,2448,NaN,VARZEA,25953-004,ETANOL,10/01/2024,3.34,NaN,R$ / litro,BRANCA
33387,SE,RJ,TERESOPOLIS,POSTO BRISA DE TERESOPOLIS LTDA,40.816.929/0001-08,RUA MANOEL JOSE LEBRAO,477,LOTE LOTE 27 28 E 29,VARZEA,25975-202,ETANOL,10/01/2024,3.30,NaN,R$ / litro,IPIRANGA
41731,SE,RJ,SANTO ANTONIO DE PADUA,GNV PADUA COMERCIO DE COMBUSTIVEL LTDA - ME,15.252.610/0001-50,ESTRADA PADUA - PIRAPETINGA,SN,KM 01 GALPAO02,ARRAIALZINHO,28470-000,ETANOL,15/01/2024,3.44,NaN,R$ / litro,BRANCA
47057,SE,RJ,TERESOPOLIS,POSTO BRISA DE TERESOPOLIS LTDA,40.816.929/0001-08,RUA MANOEL JOSE LEBRAO,477,LOTE LOTE 27 28 E 29,VARZEA,25975-202,ETANOL,16/01/2024,3.30,NaN,R$ / litro,IPIRANGA
48159,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA JARDIM SULACAP LTDA,00.773.198/0001-46,RUA EUZEBIO DE ALMEIDA,2098,NaN,JARDIM SULACAP,22725-000,ETANOL,17/01/2024,3.44,NaN,R$ / litro,BRANCA
49937,SE,RJ,TERESOPOLIS,POSTO 01 TREVO ERMITAGE DE TERESOPOLIS LTDA,12.880.259/0001-53,RUA WILHELM CRISTIAN KLEME,850,NaN,ERMITAGE,25975-550,ETANOL,17/01/2024,3.30,NaN,R$ / litro,IPIRANGA
51461,SE,RJ,TERESOPOLIS,POSTO PODIUM DE TERESOPOLIS LTDA,05.564.689/0001-09,AVENIDA LUCIO MEIRA,2448,NaN,VARZEA,25953-004,ETANOL,18/01/2024,3.34,NaN,R$ / litro,BRANCA
59618,SE,RJ,SANTO ANTONIO DE PADUA,GNV PADUA COMERCIO DE COMBUSTIVEL LTDA - ME,15.252.610/0001-50,ESTRADA PADUA - PIRAPETINGA,SN,KM 01 GALPAO02,ARRAIALZINHO,28470-000,ETANOL,22/01/2024,3.44,NaN,R$ / litro,BRANCA
69209,SE,RJ,TERESOPOLIS,POSTO PODIUM DE TERESOPOLIS LTDA,05.564.689/0001-09,AVENIDA LUCIO MEIRA,2448,NaN,VARZEA,25953-004,ETANOL,25/01/2024,3.34,NaN,R$ / litro,BRANCA
72782,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARA AZUL LTDA,04.148.976/0001-67,RUA ANGELICA MOTA,6,NaN,OLARIA,21021-490,ETANOL,29/01/2024,3.42,NaN,R$ / litro,BRANCA
72923,SE,RJ,SANTO ANTONIO DE PADUA,AUTO POSTO AEROPORTO LTDA,04.024.094/0001-90,AVENIDA JOAO JASBICK,293,NaN,AEROPORTO,28470-000,ETANOL,29/01/2024,3.44,NaN,R$ / litro,BRANCA
77905,SE,RJ,SANTO ANTONIO DE PADUA,GNV PADUA COMERCIO DE COMBUSTIVEL LTDA - ME,15.252.610/0001-50,ESTRADA PADUA - PIRAPETINGA,SN,KM 01 GALPAO02,ARRAIALZINHO,28470-000,ETANOL,29/01/2024,3.44,NaN,R$ / litro,BRANCA
79895,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA JARDIM SULACAP LTDA,00.773.198/0001-46,RUA EUZEBIO DE ALMEIDA,2098,NaN,JARDIM SULACAP,22725-000,ETANOL,30/01/2024,3.44,NaN,R$ / litro,BRANCA
91442,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARA AZUL LTDA,04.148.976/0001-67,RUA ANGELICA MOTA,6,NaN,OLARIA,21021-490,ETANOL,05/02/2024,3.42,NaN,R$ / litro,BRANCA

SP:

In [260]:
array_etanol_sp = np.array(df_etanol_sp['Valor de Venda'])
media_e_sp = np.mean(array_etanol_sp)
q1_e_sp = np.percentile(array_etanol_sp, 25)
q3_e_sp = np.percentile(array_etanol_sp, 75)
iqr_e_sp = q3_e_sp - q1_e_sp
l_sup_e_sp = q3_e_sp + (1.5*iqr_e_sp)
l_inf_e_sp = q1_e_sp - (1.5*iqr_e_sp)
print(f'Media: {media_e_sp} \nQ1: {q1_e_sp} Q3: {q3_e_sp}')
print(f'IQR: {iqr_e_sp} \nSuperior: {l_sup_e_sp} \nInferior: {l_inf_e_sp}')

Media: 3.896278944665868
Q1: 3.67 Q3: 4.09
IQR: 0.41999999999999993
Superior: 4.72
Inferior: 3.04

In [261]:
outlier_sup_e_sp = df_etanol_sp.loc[df_etanol_sp['Valor de Venda'] > l_sup_e_sp]
outlier_sup_e_sp

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
335,SE,SP,SAO PAULO,AUTO POSTO DUQUE ZAGOTTIS LTDA.,07.846.543/0001-73,AVENIDA ALBERTO DE ZAGOTTIS,567,NaN,JURUBATUBA,04676-000,ETANOL,01/01/2024,4.99,NaN,R$ / litro,VIBRA
1036,SE,SP,GUARUJA,PRL PETROLEO II LTDA.,18.018.790/0001-06,AVENIDA PUGLISI,550,NaN,CENTRO,11410-002,ETANOL,01/01/2024,4.99,NaN,R$ / litro,VIBRA
3394,SE,SP,SAO PAULO,CENTRO AUTOMOTIVO ARCO DO TRIUNFO LTDA.,04.966.902/0001-38,RUA DR. MOISES KAHAN,501,NaN,BARRA FUNDA,01139-040,ETANOL,02/01/2024,4.99,NaN,R$ / litro,VIBRA
5016,SE,SP,SAO PAULO,AUTO POSTO DUQUE DUMONT VILLARES LTDA.,07.846.559/0001-86,AVENIDA LUIS DUMONT VILLARES,1422,NaN,SANTANA,02239-000,ETANOL,02/01/2024,4.99,NaN,R$ / litro,VIBRA
9205,SE,SP,SAO PAULO,AUTO POSTO DUQUE BERRINI LTDA.,07.846.563/0001-44,AVENIDA ENHGENHEIRO LUIS CARLOS BERRINI,1264,NaN,BROOKLIN NOVO,04571-000,ETANOL,03/01/2024,4.99,NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521133,SE,SP,ITAPETININGA,AUTO POSTO APARECIDA DE ITAPETININGA LTDA,22037599000170,RUA JOSE DE ALMEIDA CARVALHO,248,NaN,CENTRO,18200-354,ETANOL,30/12/2025,4.99,NaN,R$ / litro,VIBRA
1521447,SE,SP,CARAGUATATUBA,AUTO POSTO ARQUIPELAGO LTDA,2724556000156,AVENIDA MARGINAL 2,35,NaN,JARDIM TARUMAS,11668-660,ETANOL,31/12/2025,4.99,NaN,R$ / litro,RAIZEN
1521461,SE,SP,GUARATINGUETA,POSTO JARDIM DO VALE LTDA,384366000101,RUA JOSE SEBASTIAO MARINS,725,NaN,PARQUE RESIDENCIAL BEIRA RIO I,12517-440,ETANOL,31/12/2025,4.96,NaN,R$ / litro,ALE
1521462,SE,SP,GUARATINGUETA,POSTO CLUBE DOS 500 LTDA.,7235512000186,RODOVIA PRESIDENTE DUTRA,S/N,KM 60,BELVEDERE CLUBE DOS 500,12522-640,ETANOL,31/12/2025,4.79,NaN,R$ / litro,IPIRANGA
1521485,SE,SP,SAO PAULO,CHOU GAS AUTO POSTO LTDA,4770504000141,RUA PROFESSOR CARDOZO DE MELLO NETO,1516,NaN,VILA GUACURI,04474-180,ETANOL,31/12/2025,4.89,NaN,R$ / litro,IPIRANGA

In [262]:
outlier_inf_e_sp = df_etanol_sp.loc[df_etanol_sp['Valor de Venda'] < l_inf_e_sp]
outlier_inf_e_sp

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
302,SE,SP,SAO JOSE DO RIO PRETO,AUTO POSTO DO IPE - RIO PRETO LTDA.,03.225.464/0001-94,AVENIDA ALFREDO ANTONIO DE OLIVEIRA,2800,NaN,JARDIM PLANALTO,15046-619,ETANOL,01/01/2024,2.83,NaN,R$ / litro,BRANCA
317,SE,SP,SAO JOSE DO RIO PRETO,IRMAOS PORCINI - RIO PRETO LTDA.,03.785.430/0001-54,RUA JOSINA TEIXEIRA DE CARVALHO,127,NaN,VILA ANCHIETA,15050-305,ETANOL,01/01/2024,2.74,NaN,R$ / litro,BRANCA
325,SE,SP,SAO JOSE DO RIO PRETO,POSTO ITAMARATI - JAYA LTDA,04.175.812/0001-29,"AVENIDA MARIA DA SILVA DORIA,",745,NaN,JARDIM SANTA ROSA II,15053-000,ETANOL,01/01/2024,2.99,NaN,R$ / litro,VIBRA
330,SE,SP,SAO JOSE DO RIO PRETO,AUTO POSTO ZAFANI RIO PRETO LTDA,03.389.606/0001-59,AVENIDA MONTE APRAZIVEL,2890,NaN,ELDORADO,15043-450,ETANOL,01/01/2024,2.99,NaN,R$ / litro,VIBRA
338,SE,SP,SAO PAULO,AUTO POSTO ADAMO LTDA,07.692.450/0001-31,AVENIDA ROBERT KENNEDY,4605,NaN,INTERLAGOS,04772-005,ETANOL,01/01/2024,2.93,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485662,SE,SP,SAO PAULO,FORTSUL POSTO DE SERVICOS E CONVENIENCIAS LTDA,07.674.946/0001-82,AVENIDA MORVAN DIAS DE FIGUEIREDO,5479,C,VILA MARIA,02170-000,ETANOL,02/07/2024,2.99,NaN,R$ / litro,BRANCA
486921,SE,SP,SAO CAETANO DO SUL,AUTO POSTO BAND GUIDO ALIBERTI LTDA,40.633.388/0001-82,AVENIDA GUIDO ALIBERTI,1311,NaN,SANTO ANTONIO,09530-200,ETANOL,02/07/2024,2.99,NaN,R$ / litro,BRANCA
495334,SE,SP,SAO PAULO,AUTO POSTO JARDIM CAMBARA LTDA,05.052.844/0001-08,RUA ERICO VERISSIMO,391,NaN,JARDIM CAMBARA,05560-000,ETANOL,08/07/2024,2.99,NaN,R$ / litro,BRANCA
499317,SE,SP,SAO CAETANO DO SUL,AUTO POSTO BAND GUIDO ALIBERTI LTDA,40.633.388/0001-82,AVENIDA GUIDO ALIBERTI,1311,NaN,SANTO ANTONIO,09530-200,ETANOL,08/07/2024,2.99,NaN,R$ / litro,BRANCA
503676,SE,SP,SAO PAULO,AUTO POSTO TUIM LTDA.,05.311.696/0001-90,AVENIDA BENJAMIM PEREIRA,60,NaN,VILA MAZZEI,02274-000,ETANOL,10/07/2024,2.99,NaN,R$ / litro,BRANCA

Conclusão, as estáticas são parecidas, mas ainda são um pouco distantes.

### 5. Preço da gasolina em bairros do rj municipio:

In [263]:
df_comun_rj_cap = df_comun.loc[df_comun['Municipio'] == 'RIO DE JANEIRO']
df_comun_rj_bairro = df_comun_rj_cap.groupby('Bairro')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)

O preços mais caros estão divididos entre os bairros centrais

In [264]:
df_comun_rj_bairro.head(10)

             Bairro  Valor de Venda
23         FLAMENGO        6.696667
41  JARDIM BOTANICO        6.614615
44            LAGOA        6.505385
55  PARQUE FLAMENGO        6.454706
21          ESTACIO        6.416882
33          IPANEMA        6.291923
30            GÁVEA        6.290000
26            GAVEA        6.290000
79   VARGEM PEQUENA        6.266140
45      LARANJEIRAS        6.237361

Os preços mais baratos são em bairros perifericos

In [265]:
df_comun_rj_bairro.tail(10)

               Bairro  Valor de Venda
47          MADUREIRA        5.442941
2             ANDARAÍ        5.440000
34              IRAJA        5.423333
62  QUINTINO BOCAIUVA        5.409565
68              ROCHA        5.375854
50              MEIER        5.340000
37             JACARE        5.310000
49     MARIA DA GRACA        5.290000
43     JARDIM SULACAP        5.226364
3                ANIL        5.156667

In [266]:
array_c_rj_bairro = np.array(df_comun_rj_bairro['Valor de Venda'])
q1_c_rj_bairro = np.percentile(array_c_rj_bairro, 25)
q3_c_rj_bairro = np.percentile(array_c_rj_bairro, 75)
iqr_c_rj_bairro = q3_c_rj_bairro - q1_c_rj_bairro
l_sup_c_rj_bairro = q3_c_rj_bairro + (1.5*iqr_c_rj_bairro)
l_inf_c_rj_bairro = q1_c_rj_bairro - (1.5*iqr_c_rj_bairro)
print(f'Q1: {q1_c_rj_bairro} Q3: {q3_c_rj_bairro}')
print(f'IQR: {iqr_c_rj_bairro} \nSuperior: {l_sup_c_rj_bairro} \nInferior: {l_inf_c_rj_bairro}')

Q1: 5.640000000000001 Q3: 6.060588235294118
IQR: 0.42058823529411704
Superior: 6.691470588235293
Inferior: 5.009117647058825

O unico outlier superior é o Flamengo

In [267]:
outlier_sup_c_rj_bairros = df_comun_rj_bairro.loc[df_comun_rj_bairro['Valor de Venda'] > l_sup_c_rj_bairro]
outlier_sup_c_rj_bairros

      Bairro  Valor de Venda
23  FLAMENGO        6.696667

O preço mais baixo é o Anil e ele está superior ao limite inferior, logo não faz diferença na media

In [268]:
outlier_inf_c_rj_bairros = df_comun_rj_bairro.loc[df_comun_rj_bairro['Valor de Venda'] < l_inf_c_rj_bairro]
outlier_inf_c_rj_bairros

Empty DataFrame
Columns: [Bairro, Valor de Venda]
Index: []